// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module PE_16(
  input         clock,
  input  [31:0] io_in_a,
                io_in_b,
                io_in_d,
  input         io_in_control_dataflow,
                io_in_control_propagate,
  input  [2:0]  io_in_id,
  input         io_in_last,
                io_in_valid,
  output [31:0] io_out_a,
                io_out_b,
                io_out_c,
  output        io_out_control_dataflow,
                io_out_control_propagate,
  output [2:0]  io_out_id,
  output        io_out_last,
                io_out_valid
);

// c1 is asserted for io_in_valid = 1 and io_in_control_propagate = 1
// c2 is asserted for io_in_valid = 1 and io_in_control_propagate = 0

  reg [31:0] c1;	// @[PE.scala:69:15]
  reg [31:0] c2;	// @[PE.scala:70:15]
  always @(posedge clock) begin
    if (io_in_valid & io_in_control_propagate)	// @[PE.scala:101:95, :140:17, :141:8]
      c1 <= io_in_d;	// @[PE.scala:69:15]
    if (~(~io_in_valid | io_in_control_propagate))	// @[PE.scala:70:15, :101:95, :118:30, :129:10, :140:{9,17}, :142:8]
      c2 <= io_in_d;	// @[PE.scala:70:15]
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        c1 = _RANDOM_0;	// @[PE.scala:69:15]
        c2 = _RANDOM_1;	// @[PE.scala:70:15]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  MacUnit mac_unit (	// @[PE.scala:64:24]
    .io_in_a  (io_in_a),
    .io_in_b  (io_in_control_propagate ? c2 : c1),	// @[PE.scala:69:15, :70:15, :118:30, :120:24, :126:24]
    .io_in_c  (io_in_b),
    .io_out_d (io_out_b)
  );
  assign io_out_a = io_in_a;
  assign io_out_c = io_in_control_propagate ? c1 : c2;	// @[PE.scala:69:15, :70:15, :118:30, :119:16, :125:16]
  assign io_out_control_dataflow = io_in_control_dataflow;
  assign io_out_control_propagate = io_in_control_propagate;
  assign io_out_id = io_in_id;
  assign io_out_last = io_in_last;
  assign io_out_valid = io_in_valid;
endmodule

