// Generated by CIRCT firtool-1.75.0
module MacUnit(	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:14:7]
  input  [31:0] io_in_a,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:16:14]
  input  [31:0] io_in_b,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:16:14]
  input  [31:0] io_in_c,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:16:14]
  output [31:0] io_out_d	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:16:14]
);

  assign io_out_d = io_in_a * io_in_b + io_in_c;	// @[generators/gemmini/src/main/scala/gemmini/Arithmetic.scala:93:{49,54}, generators/gemmini/src/main/scala/gemmini/PE.scala:14:7]
endmodule

